In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import DataFrame, Series 
import random 

data analysis is process of  gathering ,inspecting cleaning and transforming and modeling to extract cruicial information form it 

In [2]:
# EDA is exploratry data  analysis is process of identify all the genral pattern from the cleaned data set
# create firsrt np array 
n=np.array(range(1,6))
n
            

array([1, 2, 3, 4, 5])

In [3]:
n2=np.arange(1,13).reshape(3,4)
n2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
n3=np.array(np.random.randint(1,49,9)).reshape(3,3)
n3

array([[26, 32, 44],
       [26, 22,  2],
       [26, 19, 30]], dtype=int32)

In [5]:
# create a new 2 np array of 3,3 taking input from user
l=[]
count=1
for i in range(3):
    r=[]
    for j in range(3):
        r.append(count)
        count+=1

    l.append(r)

new=np.array(l)
new
        

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
### here we are going to use all numpy methods as '
print(new.ndim)
print(n.ndim)
print(new.shape)
print(n.shape)
print(n.size)
print(new.size)
print(new.dtype)
print(np.linspace(1,2,5))


print(new[1:,1:])
print(new[:2,:2])
print(new.flatten())

2
1
(3, 3)
(5,)
5
9
int64
[1.   1.25 1.5  1.75 2.  ]
[[5 6]
 [8 9]]
[[1 2]
 [4 5]]
[1 2 3 4 5 6 7 8 9]


In [7]:
a=new[1:,1:]
b=new[:2,:2]

In [8]:
new=new.reshape(3,3)

np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
print(new.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
print(np.concatenate([a,b]))

[[5 6]
 [8 9]
 [1 2]
 [4 5]]


In [13]:
print(np.concatenate([a,b],axis=1))

[[5 6 1 2]
 [8 9 4 5]]


In [14]:
print(np.stack([a,b],axis=0))

[[[5 6]
  [8 9]]

 [[1 2]
  [4 5]]]


In [15]:
print(np.vstack([a,b]))

[[5 6]
 [8 9]
 [1 2]
 [4 5]]


In [16]:
print(np.hstack([a,b]))

[[5 6 1 2]
 [8 9 4 5]]


In [17]:
### pandas are data analysis 
df=pd.DataFrame(np.arange(1,13).reshape(3,4) , index =list('ABC') ,columns=['c1','c2','c3','c4'])
df

c1  c2  c3  c4
A   1   2   3   4
B   5   6   7   8
C   9  10  11  12

In [18]:
df.T

A  B   C
c1  1  5   9
c2  2  6  10
c3  3  7  11
c4  4  8  12

In [20]:
df.index

Index(['A', 'B', 'C'], dtype='object')

In [21]:
df.columns

Index(['c1', 'c2', 'c3', 'c4'], dtype='object')

In [23]:
S1=Series(np.array(range(0,16,3)),index=list('abcdef'))
print(S1)

a     0
b     3
c     6
d     9
e    12
f    15
dtype: int64


In [31]:
print(S1["c"])
print(df['c2'])

6
A     2
B     6
C    10
Name: c2, dtype: int64


In [34]:
df.loc[["B",'C'],['c2','c4']]

c2  c4
B   6   8
C  10  12

In [41]:
## point to remember all df.loc require diffrent bracket for rows and columns while iloc dont need axtra bract only in one bracke we use 
df.iloc[:2 ,1:]

c2  c3  c4
A   2   3   4
B   6   7   8

In [44]:
np.random.seed(25)

DF_obj=DataFrame(np.random.randint(1,20,size=36).reshape((6,6)),
                index=['row 1','row 2','row 3','row 4','row 5','row 6'],
                columns=['col 1','col 2','col 3','col 4','col 5','col 6'])

DF_obj

col 1  col 2  col 3  col 4  col 5  col 6
row 1      5     16     13     19      9      5
row 2      6      2      8      4      4     14
row 3      4      2     17     16     10     17
row 4     13     14     19      5     10      1
row 5     11     16     11      2     18     19
row 6      5      3      6      9     12     17

In [46]:
DF_obj.head(5)

col 1  col 2  col 3  col 4  col 5  col 6
row 1      5     16     13     19      9      5
row 2      6      2      8      4      4     14
row 3      4      2     17     16     10     17
row 4     13     14     19      5     10      1
row 5     11     16     11      2     18     19

In [48]:
DF_obj.tail(3)

col 1  col 2  col 3  col 4  col 5  col 6
row 4     13     14     19      5     10      1
row 5     11     16     11      2     18     19
row 6      5      3      6      9     12     17

In [50]:
df.describe()

c1    c2    c3    c4
count  3.0   3.0   3.0   3.0
mean   5.0   6.0   7.0   8.0
std    4.0   4.0   4.0   4.0
min    1.0   2.0   3.0   4.0
25%    3.0   4.0   5.0   6.0
50%    5.0   6.0   7.0   8.0
75%    7.0   8.0   9.0  10.0
max    9.0  10.0  11.0  12.0

In [52]:
DF_obj.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, row 1 to row 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col 1   6 non-null      int32
 1   col 2   6 non-null      int32
 2   col 3   6 non-null      int32
 3   col 4   6 non-null      int32
 4   col 5   6 non-null      int32
 5   col 6   6 non-null      int32
dtypes: int32(6)
memory usage: 192.0+ bytes


In [53]:
DF_obj>10

col 1  col 2  col 3  col 4  col 5  col 6
row 1  False   True   True   True  False  False
row 2  False  False  False  False  False   True
row 3  False  False   True   True  False   True
row 4   True   True   True  False  False  False
row 5   True   True   True  False   True   True
row 6  False  False  False  False   True   True

In [74]:
Test =DF_obj[DF_obj>10]
Test

col 1  col 2  col 3  col 4  col 5  col 6
row 1    NaN   16.0   13.0   19.0    NaN    NaN
row 2    NaN    NaN    NaN    NaN    NaN   14.0
row 3    NaN    NaN   17.0   16.0    NaN   17.0
row 4   13.0   14.0   19.0    NaN    NaN    NaN
row 5   11.0   16.0   11.0    NaN   18.0   19.0
row 6    NaN    NaN    NaN    NaN   12.0   17.0

In [56]:
DF=DF_obj.T

In [62]:
DF_obj2=pd.DataFrame(np.random.randint(1,25,size=36).reshape(6,6) , index=['row 1','row 2','row 3','row 4','row 5','row 6'],columns=['col 1','col 2','col 3','col 4','col 5','col 6'])

In [63]:
DF_obj2

col 1  col 2  col 3  col 4  col 5  col 6
row 1      7     21      3      6     10     23
row 2     17     12      3     12     21     20
row 3     11     18     15     20      6     11
row 4     24     19     20     15      8     16
row 5     15     13      8     15     20     22
row 6      6     14     15     22      4      3

In [72]:
DF_obj2.loc[['row 5'],["col 2"]]  =10000

In [73]:
DF_obj2

col 1  col 2  col 3  col 4  col 5  col 6
row 1      7     21      3      6     10     23
row 2     17     12      3     12     21     20
row 3     11     18     15     20      6     11
row 4     24     19     20     15      8     16
row 5     15  10000      8     15     20     22
row 6      6     14     15     22      4      3

In [79]:
m=Test['col 3'].mean()
m
Test["col 3"].fillna(m)

row 1    13.0
row 2    15.0
row 3    17.0
row 4    19.0
row 5    11.0
row 6    15.0
Name: col 3, dtype: float64

In [80]:
DF_obj.sort_values(by="col 5")

col 1  col 2  col 3  col 4  col 5  col 6
row 2      6      2      8      4      4     14
row 1      5     16     13     19      9      5
row 3      4      2     17     16     10     17
row 4     13     14     19      5     10      1
row 6      5      3      6      9     12     17
row 5     11     16     11      2     18     19

In [84]:
d={"names":["riya","rohan","rishabh","mohit","Shivam",'shoib','Akash','Abira'],
  "age" :[25,28,27,34,37,25,30,20],
  "salary":[25000, 30000,45000,20000,34000,42000,15000,33000],
  "location":["pune","banglore","pune","hydarabad","indore","nasik","nagpur","mumbai"],
  "dept":["HR","sales","IT","finanace","csr","HR","tech","IT"]}

In [82]:
d

{'names': ['riya',
  'rohan',
  'rishabh',
  'mohit',
  'Shivam',
  'shoib',
  'Akash',
  'Abira'],
 'age': [25, 28, 27, 34, 37, 25, 30, 20],
 'salary': [25000, 30000, 45000, 20000, 34000, 42000, 15000, 33000],
 'location': ['pune',
  'banglore',
  'pune',
  'hydarabad',
  'indore',
  'nasik',
  'nagpur'],
 'dept': ['HR', 'sales', 'IT', 'finanace', 'csr', 'HR', 'tech', 'IT']}

In [86]:
DF_new=pd.DataFrame(d,index=["emp1","emp2","emp3","emp4","emp5","emp6","emp7","emp8"])
DF_new

names  age  salary   location      dept
emp1     riya   25   25000       pune        HR
emp2    rohan   28   30000   banglore     sales
emp3  rishabh   27   45000       pune        IT
emp4    mohit   34   20000  hydarabad  finanace
emp5   Shivam   37   34000     indore       csr
emp6    shoib   25   42000      nasik        HR
emp7    Akash   30   15000     nagpur      tech
emp8    Abira   20   33000     mumbai        IT

In [87]:
DF_new.loc[["emp5"]]

names  age  salary location dept
emp5  Shivam   37   34000   indore  csr

In [89]:
DF_new1=DF_new[DF_new["salary"] > 30000]
DF_new1.sort_values(by='age')

names  age  salary location dept
emp8    Abira   20   33000   mumbai   IT
emp6    shoib   25   42000    nasik   HR
emp3  rishabh   27   45000     pune   IT
emp5   Shivam   37   34000   indore  csr

In [90]:
DF_new.rename(columns={"dept" :"Department"},inplace=True)
DF_new

names  age  salary   location Department
emp1     riya   25   25000       pune         HR
emp2    rohan   28   30000   banglore      sales
emp3  rishabh   27   45000       pune         IT
emp4    mohit   34   20000  hydarabad   finanace
emp5   Shivam   37   34000     indore        csr
emp6    shoib   25   42000      nasik         HR
emp7    Akash   30   15000     nagpur       tech
emp8    Abira   20   33000     mumbai         IT

In [94]:
DF_new.rename(index={"emp1" : "emp01"})

names  age  salary   location Department
emp01     riya   25   25000       pune         HR
emp2     rohan   28   30000   banglore      sales
emp3   rishabh   27   45000       pune         IT
emp4     mohit   34   20000  hydarabad   finanace
emp5    Shivam   37   34000     indore        csr
emp6     shoib   25   42000      nasik         HR
emp7     Akash   30   15000     nagpur       tech
emp8     Abira   20   33000     mumbai         IT

In [98]:
DF_new["Department"].unique() #will give all unique values 

array(['HR', 'sales', 'IT', 'finanace', 'csr', 'tech'], dtype=object)

In [100]:
DF_new["Department"].nunique()  # it will count of uniuq values 

6

In [101]:
DF_new.groupby('Department')['salary'].mean()

Department
HR          33500.0
IT          39000.0
csr         34000.0
finanace    20000.0
sales       30000.0
tech        15000.0
Name: salary, dtype: float64