# Pandas tutorials

In [103]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [3]:
print(pd.__version__)

1.0.5


# series create series ,manipualte , quary  delete

In [54]:
s1=pd.Series([1,2,3,4,5],index=["r1","r2","r3","r4","r5"])
s1

r1    1
r2    2
r3    3
r4    4
r5    5
dtype: int64

In [14]:
#here if want to print a array we will do
s2=np.arange(8)
print(s2)

#here we will create saeries using n


s3=Series(np.arange(2,8,2))
print(s3)


# wil create using pandas 
s3=pd.Series(range(8))
print(s3)

[0 1 2 3 4 5 6 7]
0    2
1    4
2    6
dtype: int32
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
dtype: int64


In [20]:
r= int(input("how many rows you want to enter "))
c= int(input("how many columns u want  to enter"))

mix=np.zeros((r,c))
for i in range(r):
    for j in range(c):
        y=int(input(f"please enter value in  row {i} and column {j}  >> "))
        mix[i][j]=y
        
print(mix)


how many rows you want to enter 2
how many columns u want  to enter2
please enter value in  row 0 and column 0  >> 45
please enter value in  row 0 and column 1  >> 56
please enter value in  row 1 and column 0  >> 23
please enter value in  row 1 and column 1  >> 67
[[45. 56.]
 [23. 67.]]


In [21]:
mix[1][1]

67.0

In [28]:
series_obj=pd.Series(range(10) ,index=["r1","r2","r3","r4","r5","r6","r7","r8","r9","r10"])
series_obj

r1     0
r2     1
r3     2
r4     3
r5     4
r6     5
r7     6
r8     7
r9     8
r10    9
dtype: int64

In [29]:
def arr():
    l=[]
    for i in range(5):
        l.append(int(input("please enter the value")))
    
    
    return l


In [31]:
res=arr()
s=pd.Series(res,index=[1,2,3,4,5])
s

please enter the value34
please enter the value12
please enter the value56
please enter the value67
please enter the value89


1    34
2    12
3    56
4    67
5    89
dtype: int64

In [32]:
s[3]

56

In [36]:
n=np.random.randn(5)
n

array([ 0.78641148,  0.48611627, -0.55290199,  0.01774289,  1.72707266])

In [37]:
s5=pd.Series(np.random.randn(5),index=["a","b","c","d","e"])
s5

a   -0.731457
b    1.132664
c    0.250784
d   -0.006554
e    0.307620
dtype: float64

In [51]:
d={ 1 : "a" , 2 : "b", 3 : "c" ,4 : "d"}
print(d.get(6,"not found") )
d[5]="e"
print(d)
print(d.values())
# here we will create  a aseries using dictionaris
s6=pd.Series(d)
print(s6)

not found
{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e'}
dict_values(['a', 'b', 'c', 'd', 'e'])
1    a
2    b
3    c
4    d
5    e
dtype: object


we will modify the series

In [55]:
print(s1)
s1.index=["A","B","C","D","E"]
print(s1)

r1    1
r2    2
r3    3
r4    4
r5    5
dtype: int64
A    1
B    2
C    3
D    4
E    5
dtype: int64


In [59]:
print(s1[:"D"])
print(s1[:4])

A    1
B    2
C    3
D    4
dtype: int64
A    1
B    2
C    3
D    4
dtype: int64


In [67]:
s7=s1.append(s6)
print(s7)
print(s7["D"])

A    1
B    2
C    3
D    4
E    5
1    a
2    b
3    c
4    d
5    e
dtype: object
4


In [70]:
# here after append we can also drop data from the series
s7.drop(5)
s7

A    1
B    2
C    3
D    4
E    5
1    a
2    b
3    c
4    d
5    e
dtype: object

In [73]:
s8=s7.drop("A")
print(s7)
print(s8)

A    1
B    2
C    3
D    4
E    5
1    a
2    b
3    c
4    d
5    e
dtype: object
B    2
C    3
D    4
E    5
1    a
2    b
3    c
4    d
5    e
dtype: object


# Series operation

In [81]:
arr1=np.array(range(7))
arr2=np.array(range(6,15))
print(arr1)
print(arr2)

[0 1 2 3 4 5 6]
[ 6  7  8  9 10 11 12 13 14]


In [82]:
s_new=pd.Series(arr2 )
s_new

0     6
1     7
2     8
3     9
4    10
5    11
6    12
7    13
8    14
dtype: int32

In [78]:
s2_new=pd.Series(arr1)
s2_new

0    0
1    1
2    2
3    3
4    4
5    5
6    6
dtype: int32

In [83]:
s_new.add(s2_new)  # here s_new is added to s2_new

0     6.0
1     8.0
2    10.0
3    12.0
4    14.0
5    16.0
6    18.0
7     NaN
8     NaN
dtype: float64

In [85]:
s_new.sub(s2_new) # here we subtract avalunes from

0    6.0
1    6.0
2    6.0
3    6.0
4    6.0
5    6.0
6    6.0
7    NaN
8    NaN
dtype: float64

In [86]:
s_new.mul(s2_new)

0     0.0
1     7.0
2    16.0
3    27.0
4    40.0
5    55.0
6    72.0
7     NaN
8     NaN
dtype: float64

In [87]:
s_new.div(s2_new)

0    inf
1    7.0
2    4.0
3    3.0
4    2.5
5    2.2
6    2.0
7    NaN
8    NaN
dtype: float64

In [89]:
print(s_new.median())
print(s_new.max())
print(s_new.min())

10.0
14
6


In [90]:
print(s2_new.median())
print(s2_new.max())
print(s2_new.min())

3.0
6
0


# Create Dataframe

In [91]:
dates=pd.date_range("today",periods=6)
print(dates)

DatetimeIndex(['2024-05-06 17:46:09.980244', '2024-05-07 17:46:09.980244',
               '2024-05-08 17:46:09.980244', '2024-05-09 17:46:09.980244',
               '2024-05-10 17:46:09.980244', '2024-05-11 17:46:09.980244'],
              dtype='datetime64[ns]', freq='D')


In [98]:
num_arr=np.random.randn(6,4)
num_arr

array([[ 0.37471196,  0.84778587,  1.33032614, -1.13885219],
       [-0.29694782,  0.05950601,  0.15543786, -0.27278145],
       [-1.11636874, -0.02739008, -0.66901115,  0.62242507],
       [-0.23687608, -0.42477088, -0.71030421,  0.15609232],
       [ 0.24018408, -0.04019385,  0.34341988, -1.29504682],
       [ 0.12839752,  0.12313352, -1.39017384, -1.67996001]])

In [100]:
df1=pd.DataFrame(num_arr,index=dates,columns=["A","B","C","D"])
df1

A         B         C         D
2024-05-06 17:46:09.980244  0.374712  0.847786  1.330326 -1.138852
2024-05-07 17:46:09.980244 -0.296948  0.059506  0.155438 -0.272781
2024-05-08 17:46:09.980244 -1.116369 -0.027390 -0.669011  0.622425
2024-05-09 17:46:09.980244 -0.236876 -0.424771 -0.710304  0.156092
2024-05-10 17:46:09.980244  0.240184 -0.040194  0.343420 -1.295047
2024-05-11 17:46:09.980244  0.128398  0.123134 -1.390174 -1.679960

In [105]:
df2=pd.DataFrame(np.random.randn(36).reshape (6,6),index=["A","B","C","D","E","F"],columns=[1,2,3,4,5,6])
df2

1         2         3         4         5         6
A  2.064031 -0.257316 -0.414096  0.934919  0.738446  0.665874
B -1.010350  1.573367 -1.294202 -1.218339 -0.699764 -0.359455
C -1.868045  0.687399 -0.891705  1.343696 -0.798529 -1.218455
D -1.369411  2.151452 -1.000459  1.175771  0.589542 -1.519434
E -1.446112  1.528337 -0.062258  1.217290  1.097176 -0.580560
F  0.690196  0.324705 -0.591776 -0.726852 -1.364584 -1.295621

In [108]:
s1=pd.Series(np.random.randn(9))
print(s1)
df_new=pd.DataFrame(np.random.randn(25).reshape(5,5),index=["sun","mon","tue","wed","thus"] ,columns=["cake","chips","biscuit","drink","samosa"]
)
print(df_new)

0    0.171846
1    0.727856
2   -0.083310
3   -2.528521
4    0.067393
5   -0.918374
6    1.056521
7    0.441108
8   -0.551368
dtype: float64
          cake     chips   biscuit     drink    samosa
sun  -0.848054  2.075194 -0.680294  0.302105  1.790016
mon  -0.170013  0.073453  0.098000 -0.478915 -0.206391
tue   0.304131  0.818040  1.188994  1.546597  0.783852
wed  -0.599781  0.615908 -0.377108 -0.295257  1.527085
thus -0.757948  0.663475  1.680427  1.017170  0.775491


In [109]:
d={1:"a",2 :"b" ,3:"c",4:"d"}
sample=pd.Series(d)
print(sample)

1    a
2    b
3    c
4    d
dtype: object


In [112]:
d={"animal":["dog","cat","rabit","lion","goat","snake","tiger","horse"],
  "age":[6,8,np.nan,9,5,9,np.nan,9],
  "food":["chips","biscuit","samosa","choclate","icecraem","burger","pizza","momos"],
  "vistis" :[7,8,9,23,67,9,12,11]}

df3=pd.DataFrame(d,index=["a",'b','c','d','e','f','g','h'])
print(df3)

  animal  age      food  vistis
a    dog  6.0     chips       7
b    cat  8.0   biscuit       8
c  rabit  NaN    samosa       9
d   lion  9.0  choclate      23
e   goat  5.0  icecraem      67
f  snake  9.0    burger       9
g  tiger  NaN     pizza      12
h  horse  9.0     momos      11


In [113]:
df3.dtypes

animal     object
age       float64
food       object
vistis      int64
dtype: object

In [115]:
df3.head()

animal  age      food  vistis
a    dog  6.0     chips       7
b    cat  8.0   biscuit       8
c  rabit  NaN    samosa       9
d   lion  9.0  choclate      23
e   goat  5.0  icecraem      67

In [118]:
df3.tail()

animal  age      food  vistis
d   lion  9.0  choclate      23
e   goat  5.0  icecraem      67
f  snake  9.0    burger       9
g  tiger  NaN     pizza      12
h  horse  9.0     momos      11

In [129]:
df3.describe()

age     vistis
count  6.000000   8.000000
mean   7.666667  18.250000
std    1.751190  20.331186
min    5.000000   7.000000
25%    6.500000   8.750000
50%    8.500000  10.000000
75%    9.000000  14.750000
max    9.000000  67.000000

In [130]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, a to h
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   animal  8 non-null      object 
 1   age     6 non-null      float64
 2   food    8 non-null      object 
 3   vistis  8 non-null      int64  
dtypes: float64(1), int64(1), object(2)
memory usage: 320.0+ bytes


In [131]:
print(df3.index)
print(df3.columns)
df3.values

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='object')
Index(['animal', 'age', 'food', 'vistis'], dtype='object')


array([['dog', 6.0, 'chips', 7],
       ['cat', 8.0, 'biscuit', 8],
       ['rabit', nan, 'samosa', 9],
       ['lion', 9.0, 'choclate', 23],
       ['goat', 5.0, 'icecraem', 67],
       ['snake', 9.0, 'burger', 9],
       ['tiger', nan, 'pizza', 12],
       ['horse', 9.0, 'momos', 11]], dtype=object)

# here we will do transpose of the data 

In [132]:
df4=df3.T
df4

a        b       c         d         e       f      g      h
animal    dog      cat   rabit      lion      goat   snake  tiger  horse
age         6        8     NaN         9         5       9    NaN      9
food    chips  biscuit  samosa  choclate  icecraem  burger  pizza  momos
vistis      7        8       9        23        67       9     12     11

In [133]:
df5=df2.T
df5


A         B         C         D         E         F
1  2.064031 -1.010350 -1.868045 -1.369411 -1.446112  0.690196
2 -0.257316  1.573367  0.687399  2.151452  1.528337  0.324705
3 -0.414096 -1.294202 -0.891705 -1.000459 -0.062258 -0.591776
4  0.934919 -1.218339  1.343696  1.175771  1.217290 -0.726852
5  0.738446 -0.699764 -0.798529  0.589542  1.097176 -1.364584
6  0.665874 -0.359455 -1.218455 -1.519434 -0.580560 -1.295621

In [139]:
df3.sort_values(by="age")




animal  age      food  vistis
e   goat  5.0  icecraem      67
a    dog  6.0     chips       7
b    cat  8.0   biscuit       8
d   lion  9.0  choclate      23
f  snake  9.0    burger       9
h  horse  9.0     momos      11
c  rabit  NaN    samosa       9
g  tiger  NaN     pizza      12

In [138]:
df3.sort_values(by="vistis")

animal  age      food  vistis
a    dog  6.0     chips       7
b    cat  8.0   biscuit       8
c  rabit  NaN    samosa       9
f  snake  9.0    burger       9
h  horse  9.0     momos      11
g  tiger  NaN     pizza      12
d   lion  9.0  choclate      23
e   goat  5.0  icecraem      67

In [140]:



df3[2:5]

animal  age      food  vistis
c  rabit  NaN    samosa       9
d   lion  9.0  choclate      23
e   goat  5.0  icecraem      67

In [142]:
df3.loc[['c','g','h'],['age','vistis']]

age  vistis
c  NaN       9
g  NaN      12
h  9.0      11

# query DataFrame

In [147]:
df3.loc[["a","d",'e'],['age']]

age
a  6.0
d  9.0
e  5.0

In [148]:
df_copy=df3.copy()
df_copy

animal  age      food  vistis
a    dog  6.0     chips       7
b    cat  8.0   biscuit       8
c  rabit  NaN    samosa       9
d   lion  9.0  choclate      23
e   goat  5.0  icecraem      67
f  snake  9.0    burger       9
g  tiger  NaN     pizza      12
h  horse  9.0     momos      11

In [150]:
df3.isnull()

animal    age   food  vistis
a   False  False  False   False
b   False  False  False   False
c   False   True  False   False
d   False  False  False   False
e   False  False  False   False
f   False  False  False   False
g   False   True  False   False
h   False  False  False   False

In [156]:
print(df3.mean())
#here we can aslo take mean of any coulm as below
df3[["age"]].mean()

age        7.666667
vistis    18.250000
dtype: float64


age    7.666667
dtype: float64

In [157]:
print(df3[["age"]].sum())
print(df3[["vistis"]].max())

age    46.0
dtype: float64
vistis    67
dtype: int64


In [158]:
df3.sum()

animal                   dogcatrabitliongoatsnaketigerhorse
age                                                      46
food      chipsbiscuitsamosachoclateicecraemburgerpizzam...
vistis                                                  146
dtype: object

# operation for missing values in dataframe

In [160]:
#here we will fill na values with some particular data
df_copy.fillna(100)


animal    age      food  vistis
a    dog    6.0     chips       7
b    cat    8.0   biscuit       8
c  rabit  100.0    samosa       9
d   lion    9.0  choclate      23
e   goat    5.0  icecraem      67
f  snake    9.0    burger       9
g  tiger  100.0     pizza      12
h  horse    9.0     momos      11

In [161]:
df_copy[["age"]].mean()

age    7.666667
dtype: float64

In [164]:
mage=df_copy[["age"]].mean()
df_copy[["age"]].fillna(mage)

age
a  6.000000
b  8.000000
c  7.666667
d  9.000000
e  5.000000
f  9.000000
g  7.666667
h  9.000000

In [165]:
df_test=df3.copy()
df_test

animal  age      food  vistis
a    dog  6.0     chips       7
b    cat  8.0   biscuit       8
c  rabit  NaN    samosa       9
d   lion  9.0  choclate      23
e   goat  5.0  icecraem      67
f  snake  9.0    burger       9
g  tiger  NaN     pizza      12
h  horse  9.0     momos      11

# here will drop the rows having null values

In [167]:
df_test.dropna(how="any")


animal  age      food  vistis
a    dog  6.0     chips       7
b    cat  8.0   biscuit       8
d   lion  9.0  choclate      23
e   goat  5.0  icecraem      67
f  snake  9.0    burger       9
h  horse  9.0     momos      11

# dataframe file operation

In [169]:
df3.to_csv("animal.csv")

In [ ]:
df=pd.read_csv("")